### ISSUE TITLE
To-do list for lowel v0.1.0

### ISSUE THREAD

**Issue by jdeokkim** [c-krit/lowel#1]
# v0.1.0

## General
- [ ] `general.chunk_width_t`
- [ ] `general.chunk_height_t`
- [ ] `general.load_radius_c`
- [ ] `layers.layer.auto_split`
- [ ] `layers.layer.tiled`
- [ ] `bounds`
